### ISSUE TITLE
train from scratch

### ISSUE THREAD

**Issue by Moaz-Morsy** [hxuaj/tf2-faster-rcnn#2]
Can I use the same model to train a new dataset with only 2 classes ?
if yes, what shall I take into consideration to change the model to fit for the new data ?

**Comment by hxuaj** [comment]
> Can I use the same model to train a new dataset with only 2 classes ? if yes, what shall I take into consideration to change the model to fit for the new data ?

Sure you can train the model with 2 classes. On the top of my head:
1. You may have to rewrite the dataloader. I wrote the dataloader specific for PASCAL VOC.
2. Anything related to "label" should be noticed especially in the second stage, since the ROI part contains the differentiation of objects. E.g. change the output layer to 2 classes.

Last but not least, training with only 2 classes with such heavy 2-stage model may not be optimal. Well, also depends on your application. :)

**Comment by Moaz-Morsy** [comment]
Thanks for the the interpretation, That's really helpful
